version: "3.8"

services:
  db:
    build: ./sql_container
    #image: postgres:latest
    container_name: postgres_db_2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_sales
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  mongodb:
    build: ./nosql_container
    image: mongo:latest
    container_name: mongodb_container_2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo_seed:/docker-entrypoint-initdb.d/
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: car_sales
      DB_HOST: db
      DB_PORT: 5432
      USE_MONGO: False
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
      - mongodb

  frontend:
    build: ./frontend
    container_name: react_frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  mongo_data:
